kind: Template
apiVersion: v1
metadata:
  annotations:
    tags: amq-streams
  name: amq-streams
objects:
- kind: Subscription
  apiVersion: operators.coreos.com/v1alpha1
  metadata:
    name: "amq-streams"
    namespace: "${NAMESPACE}"
  spec:
    channel: "${CHANNEL}"
    installPlanApproval: "Automatic"
    source: "redhat-operators"
    sourceNamespace: "openshift-marketplace"
    name: "amq-streams"

parameters:
    #CHANNEL_ELASTICSEARCH=$(/usr/local/bin/oc get packagemanifest elasticsearch-operator -n openshift-marketplace -o jsonpath='{.status.channels[].name}')
  - name: CHANNEL
    displayName: Channel
    description: Channel
    required: true
    value: "stable"
  - name: NAMESPACE
    displayName: Namespace
    description: Namespace
    required: true
    value: "openshift-operators"
